#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

# Hash one or more font header files into a signed 32-bit int.
hash_files() {
  ruby -rdigest -e \
    'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' \
    "$@"
}

# Emit a reading-font ID define.
# When the noemoji/ directory exists, emits an #ifdef OMIT_EMOJI_FONTS block so
# the correct hash is selected at compile time.
# Usage: reading_font_id DEFINE_NAME file1 [file2 ...]
#   Files are relative paths from builtinFonts/ (e.g. ./lexenddeca_10_regular.h).
#   Noemoji counterparts are assumed to live at noemoji/<basename>.
reading_font_id() {
  local name="$1"; shift
  local files=("$@")

  if [ -d "./noemoji" ]; then
    local noemoji_files=()
    for f in "${files[@]}"; do
      noemoji_files+=("./noemoji/$(basename "$f")")
    done
    echo "#ifdef OMIT_EMOJI_FONTS"
    echo "#define ${name} ($(hash_files "${noemoji_files[@]}"))"
    echo "#else"
    echo "#define ${name} ($(hash_files "${files[@]}"))"
    echo "#endif"
  else
    echo "#define ${name} ($(hash_files "${files[@]}"))"
  fi
}

# NotoEmoji / NotoSymbols — standalone emoji font IDs (no noemoji variant needed)
echo "#define NOTOEMOJI_10_FONT_ID ($(hash_files ./notoemoji_10_regular.h))"
echo "#define NOTOEMOJI_12_FONT_ID ($(hash_files ./notoemoji_12_regular.h))"
echo "#define NOTOEMOJI_14_FONT_ID ($(hash_files ./notoemoji_14_regular.h))"
echo "#define NOTOEMOJI_16_FONT_ID ($(hash_files ./notoemoji_16_regular.h))"
echo "#define NOTOSYMBOLS_10_FONT_ID ($(hash_files ./notosymbols_10_regular.h))"
echo "#define NOTOSYMBOLS_12_FONT_ID ($(hash_files ./notosymbols_12_regular.h))"
echo "#define NOTOSYMBOLS_14_FONT_ID ($(hash_files ./notosymbols_14_regular.h))"
echo "#define NOTOSYMBOLS_16_FONT_ID ($(hash_files ./notosymbols_16_regular.h))"

# Reading fonts - support OMIT_EMOJI_FONTS
reading_font_id LEXENDDECA_8_FONT_ID \
  ./lexenddeca_8_regular.h ./lexenddeca_8_bold.h ./lexenddeca_8_bolditalic.h ./lexenddeca_8_italic.h
reading_font_id LEXENDDECA_10_FONT_ID \
  ./lexenddeca_10_regular.h ./lexenddeca_10_bold.h ./lexenddeca_10_bolditalic.h ./lexenddeca_10_italic.h
reading_font_id LEXENDDECA_12_FONT_ID \
  ./lexenddeca_12_regular.h ./lexenddeca_12_bold.h ./lexenddeca_12_bolditalic.h ./lexenddeca_12_italic.h
reading_font_id LEXENDDECA_14_FONT_ID \
  ./lexenddeca_14_regular.h ./lexenddeca_14_bold.h ./lexenddeca_14_bolditalic.h ./lexenddeca_14_italic.h
reading_font_id LEXENDDECA_15_FONT_ID \
  ./lexenddeca_15_regular.h ./lexenddeca_15_bold.h ./lexenddeca_15_bolditalic.h ./lexenddeca_15_italic.h
reading_font_id LEXENDDECA_16_FONT_ID \
  ./lexenddeca_16_regular.h ./lexenddeca_16_bold.h ./lexenddeca_16_bolditalic.h ./lexenddeca_16_italic.h
reading_font_id LEXENDDECA_18_FONT_ID \
  ./lexenddeca_18_regular.h ./lexenddeca_18_bold.h ./lexenddeca_18_bolditalic.h ./lexenddeca_18_italic.h
reading_font_id LEXENDDECA_20_FONT_ID \
  ./lexenddeca_20_regular.h ./lexenddeca_20_bold.h ./lexenddeca_20_bolditalic.h ./lexenddeca_20_italic.h

reading_font_id BOOKERLY_8_FONT_ID \
  ./bookerly_8_regular.h ./bookerly_8_bold.h ./bookerly_8_bolditalic.h ./bookerly_8_italic.h
reading_font_id BOOKERLY_10_FONT_ID \
  ./bookerly_10_regular.h ./bookerly_10_bold.h ./bookerly_10_bolditalic.h ./bookerly_10_italic.h
reading_font_id BOOKERLY_12_FONT_ID \
  ./bookerly_12_regular.h ./bookerly_12_bold.h ./bookerly_12_bolditalic.h ./bookerly_12_italic.h
reading_font_id BOOKERLY_14_FONT_ID \
  ./bookerly_14_regular.h ./bookerly_14_bold.h ./bookerly_14_bolditalic.h ./bookerly_14_italic.h
reading_font_id BOOKERLY_15_FONT_ID \
  ./bookerly_15_regular.h ./bookerly_15_bold.h ./bookerly_15_bolditalic.h ./bookerly_15_italic.h
reading_font_id BOOKERLY_16_FONT_ID \
  ./bookerly_16_regular.h ./bookerly_16_bold.h ./bookerly_16_bolditalic.h ./bookerly_16_italic.h
reading_font_id BOOKERLY_18_FONT_ID \
  ./bookerly_18_regular.h ./bookerly_18_bold.h ./bookerly_18_bolditalic.h ./bookerly_18_italic.h
reading_font_id BOOKERLY_20_FONT_ID \
  ./bookerly_20_regular.h ./bookerly_20_bold.h ./bookerly_20_bolditalic.h ./bookerly_20_italic.h

reading_font_id BOOKERLAM_8_FONT_ID \
  ./bookerlam_8_regular.h ./bookerlam_8_bold.h ./bookerlam_8_bolditalic.h ./bookerlam_8_italic.h
reading_font_id BOOKERLAM_10_FONT_ID \
  ./bookerlam_10_regular.h ./bookerlam_10_bold.h ./bookerlam_10_bolditalic.h ./bookerlam_10_italic.h
reading_font_id BOOKERLAM_12_FONT_ID \
  ./bookerlam_12_regular.h ./bookerlam_12_bold.h ./bookerlam_12_bolditalic.h ./bookerlam_12_italic.h
reading_font_id BOOKERLAM_14_FONT_ID \
  ./bookerlam_14_regular.h ./bookerlam_14_bold.h ./bookerlam_14_bolditalic.h ./bookerlam_14_italic.h
reading_font_id BOOKERLAM_15_FONT_ID \
  ./bookerlam_15_regular.h ./bookerlam_15_bold.h ./bookerlam_15_bolditalic.h ./bookerlam_15_italic.h
reading_font_id BOOKERLAM_16_FONT_ID \
  ./bookerlam_16_regular.h ./bookerlam_16_bold.h ./bookerlam_16_bolditalic.h ./bookerlam_16_italic.h
reading_font_id BOOKERLAM_18_FONT_ID \
  ./bookerlam_18_regular.h ./bookerlam_18_bold.h ./bookerlam_18_bolditalic.h ./bookerlam_18_italic.h
reading_font_id BOOKERLAM_20_FONT_ID \
  ./bookerlam_20_regular.h ./bookerlam_20_bold.h ./bookerlam_20_bolditalic.h ./bookerlam_20_italic.h

# UI fonts — no emoji variant
echo "#define UI_10_FONT_ID ($(hash_files ./ubuntu_10_regular.h ./ubuntu_10_bold.h))"
echo "#define UI_12_FONT_ID ($(hash_files ./ubuntu_12_regular.h ./ubuntu_12_bold.h))"
echo "#define SMALL_FONT_ID ($(hash_files ./inter_8_regular.h))"
