set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

# Hash one or more font header files into a signed 32-bit int.
hash_files() {
  ruby -rdigest -e \
    'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' \
    "$@"
}

# Emit a reading-font ID define.
reading_font_id() {
  local name="$1"; shift
  local files=("$@")

  if [ -d "./noemoji" ]; then
    local noemoji_files=()
    for f in "${files[@]}"; do
      noemoji_files+=("./noemoji/$(basename "$f")")
    done
    echo "#ifdef OMIT_EMOJI_FONTS"
    echo "#define ${name} ($(hash_files "${noemoji_files[@]}"))"
    echo "#else"
    echo "#define ${name} ($(hash_files "${files[@]}"))"
    echo "#endif"
  else
    echo "#define ${name} ($(hash_files "${files[@]}"))"
  fi
}

# 1. NotoEmoji / NotoSymbols
for size in 10 12 14 16; do
  echo "#define NOTOEMOJI_${size}_FONT_ID ($(hash_files ./notoemoji_${size}_regular.h))"
  echo "#define NOTOSYMBOLS_${size}_FONT_ID ($(hash_files ./notosymbols_${size}_regular.h))"
done

# 2. Reading fonts (Lexenddeca, Bookerly, Bookerlam)
# Tạo mảng để lưu danh sách ID cho phần static_assert ở cuối
font_ids_assert=()

for font in LEXENDDECA BOOKERLY BOOKERLAM; do
  # Chuyển tên font sang chữ thường để khớp với tên file
  font_lower=$(echo "$font" | tr '[:upper:]' '[:lower:]')

  for size in 8 10 12 14 15 16 18 20; do
    id_name="${font}_${size}_FONT_ID"
    font_ids_assert+=("$id_name")

    reading_font_id "$id_name" \
      "./${font_lower}_${size}_regular.h" \
      "./${font_lower}_${size}_bold.h" \
      "./${font_lower}_${size}_bolditalic.h" \
      "./${font_lower}_${size}_italic.h"
  done
done

# 3. UI fonts
echo "#define UI_10_FONT_ID ($(hash_files ./inter_10_regular.h ./inter_10_bold.h))"
echo "#define UI_12_FONT_ID ($(hash_files ./inter_12_regular.h ./inter_12_bold.h))"
echo "#define SMALL_FONT_ID ($(hash_files ./inter_8_regular.h))"

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."

# Gom toàn bộ danh sách ID cần kiểm tra (bao gồm cả Noto và UI)
for size in 10 12 14 16; do font_ids_assert+=("NOTOEMOJI_${size}_FONT_ID" "NOTOSYMBOLS_${size}_FONT_ID"); done
font_ids_assert+=("UI_10_FONT_ID" "UI_12_FONT_ID" "SMALL_FONT_ID")

for id in "${font_ids_assert[@]}"; do
  echo "static_assert(${id} != 0, \"Font ID collision with sentinel\");"
done
